[package]
name = "z157"
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Glenn Bitar"]
description = "Parser for fields filtering according to Zalando's RESTful API guideline #157"

[dependencies]
winnow = "0.6.20"

[lints.clippy]
pedantic = "warn"
