[package]
name = "z157-fuzz"
version = "0.0.0"
publish = false
edition = "2021"


[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.z157]
path = ".."

[[bin]]
name = "parse_walk"
path = "fuzz_targets/parse_walk.rs"
test = false
doc = false
bench = false
